/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const EventType = IDL.Variant({
  'conferences' : IDL.Null,
  'candidShoots' : IDL.Null,
  'outdoorPhotoShoot' : IDL.Null,
  'corporateEvents' : IDL.Null,
  'cinematicShoots' : IDL.Null,
  'birthday' : IDL.Null,
  'fashionEvents' : IDL.Null,
  'portrait' : IDL.Null,
  'babyShoot' : IDL.Null,
  'weddings' : IDL.Null,
  'parties' : IDL.Null,
  'preWedding' : IDL.Null,
});
export const BookingInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'eventType' : EventType,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, EventType, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const EventType = IDL.Variant({
    'conferences' : IDL.Null,
    'candidShoots' : IDL.Null,
    'outdoorPhotoShoot' : IDL.Null,
    'corporateEvents' : IDL.Null,
    'cinematicShoots' : IDL.Null,
    'birthday' : IDL.Null,
    'fashionEvents' : IDL.Null,
    'portrait' : IDL.Null,
    'babyShoot' : IDL.Null,
    'weddings' : IDL.Null,
    'parties' : IDL.Null,
    'preWedding' : IDL.Null,
  });
  const BookingInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'eventType' : EventType,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, EventType, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };