/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'eventType' : EventType,
}
export type EventType = { 'conferences' : null } |
  { 'candidShoots' : null } |
  { 'outdoorPhotoShoot' : null } |
  { 'corporateEvents' : null } |
  { 'cinematicShoots' : null } |
  { 'birthday' : null } |
  { 'fashionEvents' : null } |
  { 'portrait' : null } |
  { 'babyShoot' : null } |
  { 'weddings' : null } |
  { 'parties' : null } |
  { 'preWedding' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllInquiries' : ActorMethod<[], Array<BookingInquiry>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, EventType, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];