/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookingInquiry {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    eventType: EventType;
}
export type Time = bigint;
export enum EventType {
    conferences = "conferences",
    candidShoots = "candidShoots",
    outdoorPhotoShoot = "outdoorPhotoShoot",
    corporateEvents = "corporateEvents",
    cinematicShoots = "cinematicShoots",
    birthday = "birthday",
    fashionEvents = "fashionEvents",
    portrait = "portrait",
    babyShoot = "babyShoot",
    weddings = "weddings",
    parties = "parties",
    preWedding = "preWedding"
}
export interface backendInterface {
    getAllInquiries(): Promise<Array<BookingInquiry>>;
    submitInquiry(name: string, phone: string, email: string, eventType: EventType, message: string): Promise<boolean>;
}
import type { BookingInquiry as _BookingInquiry, EventType as _EventType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllInquiries(): Promise<Array<BookingInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: EventType, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_EventType_n6(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_EventType_n6(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_BookingInquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingInquiry): BookingInquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
    eventType: _EventType;
}): {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    eventType: EventType;
} {
    return {
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone,
        eventType: from_candid_EventType_n4(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conferences: null;
} | {
    candidShoots: null;
} | {
    outdoorPhotoShoot: null;
} | {
    corporateEvents: null;
} | {
    cinematicShoots: null;
} | {
    birthday: null;
} | {
    fashionEvents: null;
} | {
    portrait: null;
} | {
    babyShoot: null;
} | {
    weddings: null;
} | {
    parties: null;
} | {
    preWedding: null;
}): EventType {
    return "conferences" in value ? EventType.conferences : "candidShoots" in value ? EventType.candidShoots : "outdoorPhotoShoot" in value ? EventType.outdoorPhotoShoot : "corporateEvents" in value ? EventType.corporateEvents : "cinematicShoots" in value ? EventType.cinematicShoots : "birthday" in value ? EventType.birthday : "fashionEvents" in value ? EventType.fashionEvents : "portrait" in value ? EventType.portrait : "babyShoot" in value ? EventType.babyShoot : "weddings" in value ? EventType.weddings : "parties" in value ? EventType.parties : "preWedding" in value ? EventType.preWedding : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingInquiry>): Array<BookingInquiry> {
    return value.map((x)=>from_candid_BookingInquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    conferences: null;
} | {
    candidShoots: null;
} | {
    outdoorPhotoShoot: null;
} | {
    corporateEvents: null;
} | {
    cinematicShoots: null;
} | {
    birthday: null;
} | {
    fashionEvents: null;
} | {
    portrait: null;
} | {
    babyShoot: null;
} | {
    weddings: null;
} | {
    parties: null;
} | {
    preWedding: null;
} {
    return value == EventType.conferences ? {
        conferences: null
    } : value == EventType.candidShoots ? {
        candidShoots: null
    } : value == EventType.outdoorPhotoShoot ? {
        outdoorPhotoShoot: null
    } : value == EventType.corporateEvents ? {
        corporateEvents: null
    } : value == EventType.cinematicShoots ? {
        cinematicShoots: null
    } : value == EventType.birthday ? {
        birthday: null
    } : value == EventType.fashionEvents ? {
        fashionEvents: null
    } : value == EventType.portrait ? {
        portrait: null
    } : value == EventType.babyShoot ? {
        babyShoot: null
    } : value == EventType.weddings ? {
        weddings: null
    } : value == EventType.parties ? {
        parties: null
    } : value == EventType.preWedding ? {
        preWedding: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
